
public_gsheets_url = "https://docs.google.com/spreadsheets/d/1uCs7YknBg7LzL6D52R-QzdP1cJWrRUQr1_iUfC5fQtA/edit?usp=sharing"
sheet = "https://docs.google.com/spreadsheets/d/1uCs7YknBg7LzL6D52R-QzdP1cJWrRUQr1_iUfC5fQtA/edit#gid=1449655870"