
source_connectors = "https://docs.google.com/spreadsheets/d/1uCs7YknBg7LzL6D52R-QzdP1cJWrRUQr1_iUfC5fQtA/edit#gid=1005397266"
Transformation_at_source = "https://docs.google.com/spreadsheets/d/1uCs7YknBg7LzL6D52R-QzdP1cJWrRUQr1_iUfC5fQtA/edit#gid=1920003121"
Real_time_data_sharing = "https://docs.google.com/spreadsheets/d/1uCs7YknBg7LzL6D52R-QzdP1cJWrRUQr1_iUfC5fQtA/edit#gid=2041527389"
data_warehouse_destination = "https://docs.google.com/spreadsheets/d/1uCs7YknBg7LzL6D52R-QzdP1cJWrRUQr1_iUfC5fQtA/edit#gid=1928451694"

[snowflake]
user = "Asg"
password = "Snowflake@123"
account = "qx44572.ap-south-1.aws"
warehouse = "COMPUTE_WH"
database = "STREAMLIT"
schema = "PUBLIC"